parameters:
#    vault14.example.class: smok\Vault14Bundle\Example

services:
#    vault14.example:
#        class: %vault14.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
